name: 'OWASP BLT-Action Auto-assign Issue and unassign after 5 days'
description: 'Auto-assigns issues to users'
inputs:
    repo-token:
        description: 'The GITHUB_TOKEN, needed to update the Issue'
        required: true
    repository:
        description: 'The GITHUB_REPOSITORY, needed to update the Issue'
        required: true

runs:
    using: 'node20'
    main: 'src/index.js'

branding:
    icon: 'alert-circle'
    color: 'red'
