name: 'OWASP BLT-Action Auto-assign Issue and unassign after 24 hours'
description: 'Auto-assigns issues to users and manages issue workflow with GIFs, kudos, and automatic stale issue handling'
inputs:
    repo-token:
        description: 'The GITHUB_TOKEN, needed to update the Issue'
        required: true
    repository:
        description: 'The GITHUB_REPOSITORY, needed to update the Issue'
        required: true
    giphy-api-key:
        description: 'API key for the Giphy API'
        required: true

runs:
    using: 'node20'
    main: 'dist/index.js'

branding:
    icon: 'alert-circle'
    color: 'red'
