name: "BLT Bounty Processor"
description: "Minimal test composite action to verify YAML is valid."

inputs:
  api_base_url:
    description: "Base URL for BLT API"
    required: false
    default: ""
  blt_api_token:
    description: "BLT API token"
    required: false
    default: ""
  issue_number:
    description: "GitHub issue number"
    required: false
    default: ""
  issue_url:
    description: "Issue URL"
    required: false
    default: ""
  amount:
    description: "Bounty amount"
    required: false
    default: "0"
  commenter:
    description: "GitHub username"
    required: false
    default: ""
  owner:
    description: "Repo owner"
    required: false
    default: ""
  repo:
    description: "Repo name"
    required: false
    default: ""
  github_token:
    description: "GitHub token"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Sanity check – print inputs
      shell: bash
      run: |
        echo "BLT Bounty Processor composite action loaded correctly."
        echo "Issue: ${{ inputs.issue_url }}  Amount: ${{ inputs.amount }}"
