name: "BLT Bounty Processor"
description: "Composite action that creates a bounty in BLT, reads total, updates labels, and posts a confirmation comment."

inputs:
  api_base_url:
    description: "Base URL for BLT API (e.g. https://<ngrok-id>.ngrok-free.app/api)"
    required: true
  blt_api_token:
    description: "BLT API token value (WITHOUT the 'Token ' prefix)"
    required: true
  issue_number:
    description: "GitHub issue number"
    required: true
  issue_url:
    description: "Full issue URL (e.g. https://github.com/owner/repo/issues/123)"
    required: true
  amount:
    description: "Bounty amount (e.g. 10 or 12.50)"
    required: true
  commenter:
    description: "GitHub username of the bounty sponsor"
    required: true
  owner:
    description: "Repository owner"
    required: true
  repo:
    description: "Repository name"
    required: true
  github_token:
    description: "GITHUB_TOKEN used for GitHub API operations"
    required: true

runs:
  using: "composite"
  steps:
    # 1) Validate bounty amount format
    - name: Validate amount
      id: validate
      shell: bash
      run: |
        set -euo pipefail
        AMOUNT="${{ inputs.amount }}"
        if [[ -z "$AMOUNT" ]]; then
          echo "Amount is empty" >&2
          exit 1
        fi
        if ! echo "$AMOUNT" | grep -Eq '^[0-9]+(\.[0-9]{1,2})?$'; then
          echo "Invalid amount format: $AMOUNT" >&2
          exit 1
        fi
        # Ensure amount is strictly positive
        if ! awk -v a="$AMOUNT" 'BEGIN{ if (a>0) exit 0; else exit 1 }'; then
          echo "Amount must be greater than zero" >&2
          exit 1
        fi
        echo "amount=$AMOUNT" >> "$GITHUB_OUTPUT"
    
    
    # 2) Create bounty via BLT API
    - name: Create bounty via BLT API
      id: create_bounty
      shell: bash
      env:
        API_BASE_URL: ${{ inputs.api_base_url }}
        BLT_API_TOKEN: ${{ inputs.blt_api_token }}
        ISSUE_URL: ${{ inputs.issue_url }}
        AMOUNT: ${{ steps.validate.outputs.amount }}
        COMMENTER: ${{ inputs.commenter }}
      run: |
        set -euo pipefail
        command -v python >/dev/null 2>&1 || {
          echo "Python is required but not installed" >&2
          exit 1
        }
        
        # Basic input validation
        if [[ -z "$ISSUE_URL" ]]; then
          echo "Error: ISSUE_URL cannot be empty" >&2
          exit 1
        fi

        if [[ -z "$COMMENTER" ]]; then
          echo "Error: COMMENTER cannot be empty" >&2
          exit 1
        fi

        if ! [[ "${{ inputs.issue_number }}" =~ ^[0-9]+$ ]]; then
          echo "Error: issue_number must be numeric" >&2
          exit 1
        fi

        payload=$(python - <<'PY'
        import json, os
        data = {
            "github_issue_url": os.environ["ISSUE_URL"],
            "amount": os.environ["AMOUNT"],
            "github_username": os.environ["COMMENTER"],
        }
        print(json.dumps(data))
        PY
        )

        echo "Payload prepared."

        tmpfile=$(mktemp)
        trap 'rm -f "$tmpfile"' EXIT
        printf '%s' "$payload" > "$tmpfile"

        response_and_status=$(curl --max-time 30 --retry 3 --retry-delay 2 -sS -w "\n%{http_code}" -X POST \
          -H "Authorization: Token $BLT_API_TOKEN" \
          -H "Content-Type: application/json" \
          --data-binary @"$tmpfile" \
          "${API_BASE_URL%/}/bounties/")
        rm -f "$tmpfile"


        # Separate response body and status code
        http_body=$(printf '%s\n' "$response_and_status" | sed '$d')
        http_status=$(printf '%s\n' "$response_and_status" | tail -n1)

        echo "BLT create bounty request completed with status: $http_status"

        # Check if status code is 2xx
        if [[ ! "$http_status" =~ ^2 ]]; then
          echo "Error: BLT API returned status $http_status" >&2
          exit 1
        fi

        echo "create_response<<EOF" >> "$GITHUB_OUTPUT"
        echo "$http_body" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

    # 3) Query total bounty for this issue from BLT API
    - name: Query total bounty for issue from BLT API
      id: get_total
      shell: bash
      env:
        API_BASE_URL: ${{ inputs.api_base_url }}
        BLT_API_TOKEN: ${{ inputs.blt_api_token }}
        ISSUE_URL: ${{ inputs.issue_url }}
        FALLBACK_AMOUNT: ${{ steps.validate.outputs.amount }}
      run: |
        set -euo pipefail
        command -v python >/dev/null 2>&1 || {
          echo "Python is required but not installed" >&2
          exit 1
        }
        ISSUE_URL_ENC=$(python - <<'PY'
        import urllib.parse, os
        print(urllib.parse.quote(os.environ["ISSUE_URL"], safe="/:"))
        PY
        )

        http_response=$(mktemp)
        http_code=$(curl --max-time 30 --retry 3 --retry-delay 2 -sS -w "%{http_code}" -o "$http_response" \
          -H "Authorization: Token $BLT_API_TOKEN" \
          "${API_BASE_URL%/}/bounties/issue-total/?github_issue_url=$ISSUE_URL_ENC")

        if [ "$http_code" -ne 200 ]; then
          echo "Warning: BLT API /issue-total failed with status $http_code. Falling back to validated amount."
          resp=""
        else
          resp=$(cat "$http_response")
        fi

        rm -f "$http_response"
        echo "BLT total request completed with status: $http_code"


        total=$(python - <<'PY'
        import json, os, sys
        fallback = os.environ.get("FALLBACK_AMOUNT", "0")
        try:
            data = json.load(sys.stdin)
            value = data.get("total_amount", data.get("total"))
            if value in (None, ""):
                print(fallback)
            else:
                print(str(value))
        except Exception:
            print(fallback)
        PY
        "<<<" is not allowed; instead:
        )

        total=$(echo "$resp" | python - <<'PY'
        # python code
        PY
        )

        echo "Resolved total bounty: $total"
        echo "total=$total" >> "$GITHUB_OUTPUT"

    # 4) Update labels and post confirmation comment on GitHub
    - name: Update issue labels and post confirmation comment
      uses: actions/github-script@v7
      env:
        OWNER: ${{ inputs.owner }}
        REPO: ${{ inputs.repo }}
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        TOTAL: ${{ steps.get_total.outputs.total }}
        VALIDATED_AMOUNT: ${{ steps.validate.outputs.amount }}
        COMMENTER: ${{ inputs.commenter }}
        ISSUE_URL: ${{ inputs.issue_url }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const core = require('@actions/core');

          const owner = process.env.OWNER;
          const repo = process.env.REPO;
          const issue_number = parseInt(process.env.ISSUE_NUMBER, 10);
          let total = process.env.TOTAL;
          const commenter = process.env.COMMENTER;
          const issue_url = process.env.ISSUE_URL;

          // Validate/sanitize total coming from BLT API
          const amountPattern = /^\d+(?:\.\d{1,2})?$/;
          if (!amountPattern.test(total)) {
            core.warning(`Invalid total from BLT API: "${total}", falling back to validated input amount.`);
            total = process.env.VALIDATED_AMOUNT;
          }
          async function retry(fn, attempts = 5) {
            for (let i = 0; i < attempts; i++) {
              try { return await fn(); }
              catch (err) {
                await new Promise(r => setTimeout(r, 500 * (i+1)));
              }
            }
            throw new Error("Operation failed after retries");
          }

          const bountyLabelPattern = /^\$\d+(?:\.\d{1,2})?\s+Bounty$/;

          // 1) Remove existing "$X Bounty" labels
          const existing = await github.rest.issues.listLabelsOnIssue({
            owner,
            repo,
            issue_number,
          });

          for (const label of existing.data) {
            if (bountyLabelPattern.test(label.name)) {
              try {
                await retry(() => github.rest.issues.removeLabel({
                  owner,
                  repo,
                  issue_number,
                  name: label.name,
                }));
              } catch (error) {
                core.warning(`Failed to remove label ${label.name}: ${error}`);
              }
            }
          }

          // 2) Ensure new label exists
          const newLabelName = `$${total} Bounty`;

          try {
            await retry(() => github.rest.issues.createLabel({
              owner,
              repo,
              name: newLabelName,
              color: "ffd700",
              description: `Total bounty: $${total}`,
            }));
          } catch (error) {
            core.info(`Label may already exist: ${error}`);
          }

          // 3) Attach label to the issue
          try {
            await retry(() => github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: [newLabelName],
            }));
          } catch (error) {
            core.warning(`Failed to add label ${newLabelName}: ${error}`);
          }

          // 4) Post confirmation comment
          const body =
            `💰 A bounty has been added!\n` +
            `This issue now has a total bounty of $${total} thanks to @${commenter}.\n\n` +
            `Issue: ${issue_url}`;

          try {
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body,
            });
          } catch (error) {
            core.warning(`Failed to post confirmation comment: ${error}`);
          }
