name: "BLT Bounty Processor (test)"
description: "Minimal test composite action to verify YAML is valid."

inputs:
  dummy:
    description: "Dummy input"
    required: false

runs:
  using: "composite"
  steps:
    - name: Say hello
      shell: bash
      run: |
        echo "Hello from BLT-ACTION composite test"
