name: "BLT Bounty Processor"
description: "Create a bounty in BLT API, compute total, update labels, and post a confirmation comment."

inputs:
  api_base_url:
    description: "Base URL for BLT API (e.g. https://your-ngrok-url/api)"
    required: true
  blt_api_token:
    description: "Token for BLT API (without the 'Token ' prefix)"
    required: true
  issue_number:
    description: "GitHub issue number"
    required: true
  issue_url:
    description: "Full issue URL (https://github.com/owner/repo/issues/123)"
    required: true
  amount:
    description: "Bounty amount (e.g. 50 or 12.50)"
    required: true
  commenter:
    description: "GitHub username of the sponsor"
    required: true
  owner:
    description: "Repository owner"
    required: true
  repo:
    description: "Repository name"
    required: true
  github_token:
    description: "GITHUB_TOKEN used for GitHub API operations"
    required: true

runs:
  using: "composite"
  steps:
    # 1) Validate amount format
    - name: Validate amount
      id: validate
      shell: bash
      run: |
        set -euo pipefail
        AMOUNT="${{ inputs.amount }}"
        if [[ -z "$AMOUNT" ]]; then
          echo "No amount provided" >&2
          exit 1
        fi
        if ! echo "$AMOUNT" | grep -E '^[0-9]+(\.[0-9]{1,2})?$' >/dev/null; then
          echo "Invalid amount format: $AMOUNT" >&2
          exit 1
        fi
        echo "amount=$AMOUNT" >> "$GITHUB_OUTPUT"

    # 2) Create bounty in BLT API
    - name: Create bounty via BLT API
      id: create_bounty
      shell: bash
      env:
        API_BASE_URL: ${{ inputs.api_base_url }}
        BLT_API_TOKEN: ${{ inputs.blt_api_token }}
        ISSUE_URL: ${{ inputs.issue_url }}
        AMOUNT: ${{ inputs.amount }}
        COMMENTER: ${{ inputs.commenter }}
      run: |
        set -euo pipefail
        payload=$(python - <<'PY'
import json, os
print(json.dumps({
  "github_issue_url": os.environ["ISSUE_URL"],
  "amount": os.environ["AMOUNT"],
  "github_username": os.environ["COMMENTER"],
}))
PY
)
        resp=$(curl -sS -X POST \
          -H "Authorization: Token $BLT_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d "$payload" \
          "$API_BASE_URL/bounties/" || true)

        echo "create_response<<EOF" >> "$GITHUB_OUTPUT"
        echo "$resp" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

    # 3) Query total bounty for this issue
    - name: Query total bounty for issue from BLT API
      id: get_total
      shell: bash
      env:
        API_BASE_URL: ${{ inputs.api_base_url }}
        BLT_API_TOKEN: ${{ inputs.blt_api_token }}
        ISSUE_URL: ${{ inputs.issue_url }}
        FALLBACK_AMOUNT: ${{ inputs.amount }}
      run: |
        set -euo pipefail
        ISSUE_URL_ENC=$(python - <<'PY'
import urllib.parse, os
print(urllib.parse.quote(os.environ["ISSUE_URL"], safe=''))
PY
)
        resp=$(curl -sS \
          -H "Authorization: Token $BLT_API_TOKEN" \
          "$API_BASE_URL/bounties/issue-total/?github_issue_url=$ISSUE_URL_ENC" || true)

        total=$(python - <<'PY'
import json, sys, os
try:
  data = json.load(sys.stdin)
  print(data.get("total") or os.environ["FALLBACK_AMOUNT"])
except Exception:
  print(os.environ["FALLBACK_AMOUNT"])
PY
<<<"$resp")

        echo "total=$total" >> "$GITHUB_OUTPUT"

    # 4) Update labels and post confirmation comment
    - name: Update issue labels and post confirmation comment
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const owner = "${{ inputs.owner }}";
          const repo = "${{ inputs.repo }}";
          const issue_number = parseInt("${{ inputs.issue_number }}", 10);
          const total = `${{ steps.get_total.outputs.total }}` || `${{ inputs.amount }}`;
          const commenter = "${{ inputs.commenter }}";

          const existing = await github.rest.issues.listLabelsOnIssue({ owner, repo, issue_number });
          const bountyLabelPattern = /^\$\d+(?:\.\d{1,2})?\s+Bounty$/i;

          for (const label of existing.data) {
            if (bountyLabelPattern.test(label.name)) {
              try {
                await github.rest.issues.removeLabel({
                  owner,
                  repo,
                  issue_number,
                  name: label.name,
                });
              } catch (err) {
                core.warning(`Failed to remove label ${label.name}: ${err}`);
              }
            }
          }

          const newLabelName = `$${total} Bounty`;

          try {
            await github.rest.issues.createLabel({
              owner,
              repo,
              name: newLabelName,
              color: "ffd700",
              description: `Total bounty: $${total}`,
            });
          } catch (err) {
            core.info(`Label may already exist: ${err}`);
          }

          try {
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: [newLabelName],
            });
          } catch (err) {
            core.warning(`Failed to add label ${newLabelName}: ${err}`);
          }

          const body = [
            `💰 A bounty has been added!`,
            `This issue now has a total bounty of $${total} thanks to @${commenter}.`,
            ``,
            `Want to contribute? Solve this issue and claim the reward.`,
          ].join("\n");

          try {
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body,
            });
          } catch (err) {
            core.warning(`Failed to post confirmation comment: ${err}`);
          }
