name: "BLT Bounty Processor"
description: "Composite action that creates a bounty in BLT, computes total bounty for an issue, updates labels, and posts a confirmation comment."

inputs:
  api_base_url:
    description: "Base URL for BLT API (e.g. https://your-ngrok-url/api/v1)"
    required: true
  blt_api_token:
    description: "Token for BLT API (Token <value>)"
    required: true
  issue_number:
    description: "Issue number (integer)"
    required: true
  issue_url:
    description: "Full issue HTML URL (e.g. https://github.com/owner/repo/issues/123)"
    required: true
  amount:
    description: "Bounty amount (decimal string like 50 or 12.50)"
    required: true
  commenter:
    description: "GitHub username of the user who placed the bounty"
    required: true
  owner:
    description: "Repository owner"
    required: true
  repo:
    description: "Repository name"
    required: true
  github_token:
    description: "GITHUB_TOKEN used for GitHub API operations (issues/labels/comments)"
    required: true

runs:
  using: "composite"
  steps:
    # 1) Validate bounty amount
    - name: Validate amount
      id: validate
      shell: bash
      run: |
        set -euo pipefail
        AMOUNT="${{ inputs.amount }}"
        if [[ -z "$AMOUNT" ]]; then
          echo "No amount provided" >&2
          exit 1
        fi
        if ! echo "$AMOUNT" | grep -E '^[0-9]+(\.[0-9]{1,2})?$' >/dev/null; then
          echo "Invalid amount format: $AMOUNT" >&2
          exit 1
        fi
        echo "amount=$AMOUNT" >> "$GITHUB_OUTPUT"

    # 2) Create bounty in BLT
    - name: Create bounty via BLT API
      id: create_bounty
      shell: bash
      env:
        API_BASE_URL: ${{ inputs.api_base_url }}
        BLT_API_TOKEN: ${{ inputs.blt_api_token }}
      run: |
        set -euo pipefail

        payload=$(python - << 'PY'
import json
data = {
  "github_issue_url": "${{ inputs.issue_url }}",
  "amount": "${{ inputs.amount }}",
  "github_username": "${{ inputs.commenter }}"
}
print(json.dumps(data))
PY
)
        echo "Payload: $payload"

        resp=$(curl -sS -X POST \
          -H "Authorization: Token $BLT_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d "$payload" \
          "$API_BASE_URL/bounties/" || true)

        echo "create_response<<EOF" >> "$GITHUB_OUTPUT"
        echo "$resp" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

    # 3) Get total bounty for this issue
    - name: Query total bounty for issue from BLT API
      id: get_total
      shell: bash
      env:
        API_BASE_URL: ${{ inputs.api_base_url }}
        BLT_API_TOKEN: ${{ inputs.blt_api_token }}
      run: |
        set -euo pipefail

        ISSUE_URL="${{ inputs.issue_url }}"
        FALLBACK_AMOUNT="${{ inputs.amount }}"

        ISSUE_URL_ENC=$(python - << 'PY'
import urllib.parse, os
print(urllib.parse.quote(os.environ["ISSUE_URL"], safe=''))
PY
)
        echo "Encoded issue URL: $ISSUE_URL_ENC"

        resp=$(curl -sS \
          -H "Authorization: Token $BLT_API_TOKEN" \
          "$API_BASE_URL/bounties/total/?github_issue_url=$ISSUE_URL_ENC" || true)

        total=$(python - << 'PY'
import sys, json, os
fallback = os.environ["FALLBACK_AMOUNT"]
try:
    data = json.load(sys.stdin)
    value = data.get("total")
    if value is None:
        print(fallback)
    else:
        print(str(value))
except Exception:
    print(fallback)
PY
 <<< "$resp")

        echo "total=$total" >> "$GITHUB_OUTPUT"

    # 4) Update labels + post confirmation comment on GitHub
    - name: Update labels and post confirmation
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const owner = "${{ inputs.owner }}";
          const repo = "${{ inputs.repo }}";
          const issue_number = parseInt("${{ inputs.issue_number }}", 10);
          const total = "${{ steps.get_total.outputs.total }}" || "${{ inputs.amount }}";
          const commenter = "${{ inputs.commenter }}";
          const issue_url = "${{ inputs.issue_url }}";

          // Remove old "$X Bounty" labels
          const existing = await github.rest.issues.listLabelsOnIssue({
            owner,
            repo,
            issue_number,
          });

          const pattern = /^\$\d+(?:\.\d{1,2})?\s+Bounty$/i;
          for (const label of existing.data) {
            if (pattern.test(label.name)) {
              try {
                await github.rest.issues.removeLabel({
                  owner,
                  repo,
                  issue_number,
                  name: label.name,
                });
              } catch (err) {
                core.warning(`Failed to remove label ${label.name}: ${err}`);
              }
            }
          }

          // Ensure new label exists
          const newLabelName = `$${total} Bounty`;
          try {
            await github.rest.issues.createLabel({
              owner,
              repo,
              name: newLabelName,
              color: "ffd700",
              description: `Total bounty on this issue: $${total}`,
            });
          } catch (err) {
            // OK if it already exists
            core.info(`createLabel may have failed (likely exists): ${err.message}`);
          }

          // Add new label to issue
          try {
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: [newLabelName],
            });
          } catch (err) {
            core.warning(`Failed to add label ${newLabelName}: ${err}`);
          }

          // Post confirmation comment
          const body =
            `💰 A bounty has been added!\n` +
            `This issue now has a total bounty of $${total} thanks to @${commenter}.\n\n` +
            `Issue: ${issue_url}\n` +
            `Want to contribute? Solve this issue and claim the reward.`;

          try {
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body,
            });
          } catch (err) {
            core.warning(`Failed to post confirmation comment: ${err}`);
          }
