const nock = require('nock');
const assert = require('assert');
const axios = require('axios');

const attribution = '\n\n---\n*This comment was generated by [OWASP BLT-Action](https://github.com/OWASP-BLT/BLT-Action)*';

async function assignUserToIssue(owner, repo, issueNumber, username) {
  const url = `https://api.github.com/repos/${owner}/${repo}/issues/${issueNumber}/assignees`;
  const response = await axios.post(url, { assignees: [username] });
  return response.data;
}

async function postGiphyComment(owner, repo, issueNumber, searchText, giphyApiKey) {
  const giphyResponse = await axios.get(`https://api.giphy.com/v1/gifs/search?api_key=${giphyApiKey}&q=${searchText}&limit=1`);
  const gifUrl = giphyResponse.data.data[0]?.images?.original?.url;

  if (gifUrl) {
    const url = `https://api.github.com/repos/${owner}/${repo}/issues/${issueNumber}/comments`;
    const response = await axios.post(url, { body: `![Giphy GIF](${gifUrl})` });
    return response.data;
  } else {
    throw new Error(`No GIFs found for "${searchText}".`);
  }
}

describe('GitHub API Mock Test', () => {
  beforeEach(() => {
    nock.cleanAll();
  });

  it('should assign a user to an issue with a PR', async () => {
    const owner = 'testowner';
    const repo = 'testrepo';
    const issueNumber = 1;
    const username = 'testuser';

    const scope = nock('https://api.github.com')
      .post(`/repos/${owner}/${repo}/issues/${issueNumber}/assignees`, { assignees: [username] })
      .reply(201, { status: 'success' });

    const result = await assignUserToIssue(owner, repo, issueNumber, username);
    assert.strictEqual(result.status, 'success');

    scope.done();
  });

  it('should post a Giphy comment on an issue', async () => {
    const owner = 'testowner';
    const repo = 'testrepo';
    const issueNumber = 1;
    const searchText = 'funny cat';
    const giphyApiKey = 'testapikey';

    const giphyScope = nock('https://api.giphy.com')
      .get(`/v1/gifs/search?api_key=${giphyApiKey}&q=${searchText}&limit=1`)
      .reply(200, {
        data: [
          {
            images: {
              original: {
                url: 'https://giphy.com/gifs/moodman-dog-confused-rigley-beans-Z5xk7fGO5FjjTElnpT'
              }
            }
          }
        ]
      });

    const githubScope = nock('https://api.github.com')
      .post(`/repos/${owner}/${repo}/issues/${issueNumber}/comments`, { body: '![Giphy GIF](https://giphy.com/gifs/moodman-dog-confused-rigley-beans-Z5xk7fGO5FjjTElnpT)' })
      .reply(201, { status: 'success' });

    const result = await postGiphyComment(owner, repo, issueNumber, searchText, giphyApiKey);
    assert.strictEqual(result.status, 'success');

    giphyScope.done();
    githubScope.done();
  });

  it('should include attribution in comment bodies', () => {
    // Test various comment bodies to ensure they include the attribution
    const testComments = [
      'You have been unassigned from this issue. It\'s now open for others. You can reassign it anytime by typing /assign.',
      'You cannot be assigned to this issue because you are already assigned to the following issues without an open pull request: #1. Please submit a pull request for these issues before getting assigned to a new one.',
      'Hello @user! You\'ve been assigned to [repo issue #1](https://github.com/owner/repo/issues/1). You have 24 hours to complete a pull request.',
      'No GIFs found for "test".',
      '🎉 Kudos from @sender to @receiver! 🎉\n\nawesome work\n\n✅ Kudos successfully sent to the team API!',
      '⚠️ Failed to send kudos to the team API. Please try again later.',
      '⚠️ Invalid /kudos command format. Use: `/kudos receiver comment(optional)`',
      '⏰ This issue has been automatically unassigned from user due to 24 hours of inactivity. The issue is now available for anyone to work on again.'
    ];

    // Each comment should end with the attribution
    testComments.forEach((comment, index) => {
      const commentWithAttribution = comment + attribution;
      assert.ok(
        commentWithAttribution.includes('OWASP BLT-Action'),
        `Comment ${index + 1} should include attribution`
      );
      assert.ok(
        commentWithAttribution.includes('https://github.com/OWASP-BLT/BLT-Action'),
        `Comment ${index + 1} should include repository link`
      );
    });
  });
});