const nock = require('nock');
const assert = require('assert');
const axios = require('axios');

const attribution = '\n\n---\n*This comment was generated by [OWASP BLT-Action](https://github.com/OWASP-BLT/BLT-Action)*';

async function assignUserToIssue(owner, repo, issueNumber, username) {
  const url = `https://api.github.com/repos/${owner}/${repo}/issues/${issueNumber}/assignees`;
  const response = await axios.post(url, { assignees: [username] });
  return response.data;
}

async function unassignUserFromIssue(owner, repo, issueNumber, username) {
  const url = `https://api.github.com/repos/${owner}/${repo}/issues/${issueNumber}/assignees`;
  const response = await axios.delete(url, { data: { assignees: [username] } });
  return response.data;
}

async function addLabelToIssue(owner, repo, issueNumber, labels) {
  const url = `https://api.github.com/repos/${owner}/${repo}/issues/${issueNumber}/labels`;
  const response = await axios.post(url, { labels });
  return response.data;
}

async function removeLabelFromIssue(owner, repo, issueNumber, labelName) {
  const url = `https://api.github.com/repos/${owner}/${repo}/issues/${issueNumber}/labels/${labelName}`;
  const response = await axios.delete(url);
  return response.data;
}

async function postGiphyComment(owner, repo, issueNumber, searchText, giphyApiKey) {
  const giphyResponse = await axios.get(`https://api.giphy.com/v1/gifs/search?api_key=${giphyApiKey}&q=${searchText}&limit=1`);
  const gifUrl = giphyResponse.data.data[0]?.images?.original?.url;

  if (gifUrl) {
    const url = `https://api.github.com/repos/${owner}/${repo}/issues/${issueNumber}/comments`;
    const response = await axios.post(url, { body: `![Giphy GIF](${gifUrl})` });
    return response.data;
  } else {
    throw new Error(`No GIFs found for "${searchText}".`);
  }
}

async function postTipComment(owner, repo, issueNumber, receiver, amount) {
  const sponsorUrl = `https://github.com/sponsors/${receiver}`;
  
  // Check if GitHub Sponsors is enabled
  await axios.head(sponsorUrl);
  
  const url = `https://api.github.com/repos/${owner}/${repo}/issues/${issueNumber}/comments`;
  const response = await axios.post(url, {
    body: `💰 **Tip Request from @sender to @${receiver}**\n\nAmount: **$${amount}**\n\nTo complete this tip, please visit @${receiver}'s GitHub Sponsors page and select a one-time payment:\n\n🔗 [Sponsor @${receiver}](${sponsorUrl})\n\n*Note: GitHub Sponsors does not support automated payments via API. Please complete the transaction manually by selecting "One-time" on the sponsor page and entering your desired amount.*`
  });
  return response.data;
}

async function sendKudos(sender, receiver, comment, link) {
  const response = await axios.post('https://owaspblt.org/teams/give-kudos/', {
    kudosReceiver: receiver,
    kudosSender: sender,
    link: link,
    comment: comment
  });
  return response.data;
}

describe('GitHub API Mock Test', () => {
  beforeEach(() => {
    nock.cleanAll();
  });

  describe('Assignment Management', () => {
    it('should assign a user to an issue with a PR', async () => {
      const owner = 'testowner';
      const repo = 'testrepo';
      const issueNumber = 1;
      const username = 'testuser';

      const scope = nock('https://api.github.com')
        .post(`/repos/${owner}/${repo}/issues/${issueNumber}/assignees`, { assignees: [username] })
        .reply(201, { status: 'success' });

      const result = await assignUserToIssue(owner, repo, issueNumber, username);
      assert.strictEqual(result.status, 'success');

      scope.done();
    });

    it('should unassign a user from an issue', async () => {
      const owner = 'testowner';
      const repo = 'testrepo';
      const issueNumber = 1;
      const username = 'testuser';

      const scope = nock('https://api.github.com')
        .delete(`/repos/${owner}/${repo}/issues/${issueNumber}/assignees`, { assignees: [username] })
        .reply(200, { status: 'success' });

      const result = await unassignUserFromIssue(owner, repo, issueNumber, username);
      assert.strictEqual(result.status, 'success');

      scope.done();
    });

    it('should detect all assignment keywords', () => {
      const assignKeywords = [
        '/assign',
        'assign to me',
        'assign this to me',
        'assign it to me',
        'assign me this',
        'work on this',
        'i can try fixing this',
        'i am interested in doing this',
        'be assigned this',
        'i am interested in contributing'
      ];

      assignKeywords.forEach(keyword => {
        const testComment = `I would like to ${keyword}`.toLowerCase();
        assert.ok(
          assignKeywords.some(k => testComment.includes(k)),
          `Keyword "${keyword}" should be detected in comment`
        );
      });
    });
  });

  describe('Label Management', () => {
    it('should add "assigned" label to an issue', async () => {
      const owner = 'testowner';
      const repo = 'testrepo';
      const issueNumber = 1;

      const scope = nock('https://api.github.com')
        .post(`/repos/${owner}/${repo}/issues/${issueNumber}/labels`, { labels: ['assigned'] })
        .reply(200, { status: 'success' });

      const result = await addLabelToIssue(owner, repo, issueNumber, ['assigned']);
      assert.strictEqual(result.status, 'success');

      scope.done();
    });

    it('should remove "assigned" label from an issue', async () => {
      const owner = 'testowner';
      const repo = 'testrepo';
      const issueNumber = 1;

      const scope = nock('https://api.github.com')
        .delete(`/repos/${owner}/${repo}/issues/${issueNumber}/labels/assigned`)
        .reply(200, { status: 'success' });

      const result = await removeLabelFromIssue(owner, repo, issueNumber, 'assigned');
      assert.strictEqual(result.status, 'success');

      scope.done();
    });
  });

  describe('Giphy Integration', () => {
    it('should post a Giphy comment on an issue', async () => {
      const owner = 'testowner';
      const repo = 'testrepo';
      const issueNumber = 1;
      const searchText = 'funny cat';
      const giphyApiKey = 'testapikey';

      const giphyScope = nock('https://api.giphy.com')
        .get(`/v1/gifs/search?api_key=${giphyApiKey}&q=${searchText}&limit=1`)
        .reply(200, {
          data: [
            {
              images: {
                original: {
                  url: 'https://giphy.com/gifs/moodman-dog-confused-rigley-beans-Z5xk7fGO5FjjTElnpT'
                }
              }
            }
          ]
        });

      const githubScope = nock('https://api.github.com')
        .post(`/repos/${owner}/${repo}/issues/${issueNumber}/comments`, { body: '![Giphy GIF](https://giphy.com/gifs/moodman-dog-confused-rigley-beans-Z5xk7fGO5FjjTElnpT)' })
        .reply(201, { status: 'success' });

      const result = await postGiphyComment(owner, repo, issueNumber, searchText, giphyApiKey);
      assert.strictEqual(result.status, 'success');

      giphyScope.done();
      githubScope.done();
    });

    it('should handle no GIFs found scenario', async () => {
      const owner = 'testowner';
      const repo = 'testrepo';
      const issueNumber = 1;
      const searchText = 'nonexistentgif12345';
      const giphyApiKey = 'testapikey';

      const giphyScope = nock('https://api.giphy.com')
        .get(`/v1/gifs/search?api_key=${giphyApiKey}&q=${searchText}&limit=1`)
        .reply(200, {
          data: []
        });

      try {
        await postGiphyComment(owner, repo, issueNumber, searchText, giphyApiKey);
        assert.fail('Should have thrown an error');
      } catch (error) {
        assert.ok(error.message.includes('No GIFs found'));
      }

      giphyScope.done();
    });
  });

  it('should post a tip comment with GitHub Sponsors link', async () => {
    const owner = 'testowner';
    const repo = 'testrepo';
    const issueNumber = 1;
    const receiver = 'testuser';
    const amount = '10';

    // Mock the HEAD request to check if sponsors page exists
    const sponsorScope = nock('https://github.com')
      .head(`/sponsors/${receiver}`)
      .reply(200);

    const githubScope = nock('https://api.github.com')
      .post(`/repos/${owner}/${repo}/issues/${issueNumber}/comments`, (body) => {
        return body.body.includes('Tip Request') && 
               body.body.includes(`@${receiver}`) && 
               body.body.includes(`$${amount}`) &&
               body.body.includes(`https://github.com/sponsors/${receiver}`);
      })
      .reply(201, { status: 'success' });

    const result = await postTipComment(owner, repo, issueNumber, receiver, amount);
    assert.strictEqual(result.status, 'success');

    sponsorScope.done();
    githubScope.done();
  });

  describe('Kudos System', () => {
    it('should send kudos to BLT API when user has profile', async () => {
      const owner = 'testowner';
      const repo = 'testrepo';
      const issueNumber = 1;
      const sender = 'githubuser';
      const receiver = 'bltuser';
      const comment = 'Great work on the PR!';
      const link = `https://github.com/${owner}/${repo}/issues/${issueNumber}`;

      const bltScope = nock('https://owaspblt.org')
        .post('/teams/give-kudos/', {
          kudosReceiver: receiver,
          kudosSender: sender,
          link: link,
          comment: comment
        })
        .reply(201, { success: true, message: 'Kudos sent successfully!' });

      const result = await sendKudos(sender, receiver, comment, link);
      assert.strictEqual(result.success, true);

      bltScope.done();
    });

    it('should handle kudos when user does not have BLT profile', async () => {
      const owner = 'testowner';
      const repo = 'testrepo';
      const issueNumber = 1;
      const sender = 'githubuser';
      const receiver = 'newuser';
      const comment = 'Great work on the PR!';
      const link = `https://github.com/${owner}/${repo}/issues/${issueNumber}`;

      const bltScope = nock('https://owaspblt.org')
        .post('/teams/give-kudos/', {
          kudosReceiver: receiver,
          kudosSender: sender,
          link: link,
          comment: comment
        })
        .reply(404, { success: false, error: 'Receiver username not found' });

      try {
        await sendKudos(sender, receiver, comment, link);
        assert.fail('Should have thrown an error');
      } catch (error) {
        assert.strictEqual(error.response.status, 404);
      }

      bltScope.done();
    });
  });

  describe('Command Detection', () => {
    it('should detect /unassign command', () => {
      const testComments = [
        '/unassign',
        '/unassign me',
        '/unassign please'
      ];

      testComments.forEach(comment => {
        assert.ok(
          comment.toLowerCase().startsWith('/unassign'),
          `Command "${comment}" should be detected as /unassign`
        );
      });
    });

    it('should detect /giphy command', () => {
      const testComments = [
        '/giphy celebration',
        '/giphy funny cat',
        '/giphy winning'
      ];

      testComments.forEach(comment => {
        assert.ok(
          comment.toLowerCase().startsWith('/giphy'),
          `Command "${comment}" should be detected as /giphy`
        );
      });
    });

    it('should detect /kudos command', () => {
      const testComments = [
        '/kudos @user great work',
        '/kudos @contributor awesome',
        '/kudos @dev'
      ];

      testComments.forEach(comment => {
        assert.ok(
          comment.toLowerCase().startsWith('/kudos'),
          `Command "${comment}" should be detected as /kudos`
        );
      });
    });
  });

  describe('Attribution', () => {
    it('should include attribution in comment bodies', () => {
      // Test various comment bodies to ensure they include the attribution
      const testComments = [
        'You have been unassigned from this issue. It\'s now open for others. You can reassign it anytime by typing /assign.',
        'You cannot be assigned to this issue because you are already assigned to the following issues without an open pull request: #1. Please submit a pull request for these issues before getting assigned to a new one.',
        'Hello @user! You\'ve been assigned to [repo issue #1](https://github.com/owner/repo/issues/1). You have 24 hours to complete a pull request.',
        'No GIFs found for "test".',
        '🎉 Kudos from @sender to @receiver! 🎉\n\nawesome work',
        '✅ Kudos tracked on BLT profile',
        '💡 @receiver - Create a BLT profile to track all your kudos in one place!',
        '⚠️ Invalid /kudos command format.\n\nUsage: `/kudos @username [optional comment]`\n\nExample: `/kudos @alice Great work on the PR!`',
        '⏰ This issue has been automatically unassigned from user due to 24 hours of inactivity. The issue is now available for anyone to work on again.',
        '💰 **Tip Request from @sender to @receiver**\n\nAmount: **$10**\n\nTo complete this tip, please visit @receiver\'s GitHub Sponsors page and select a one-time payment:\n\n🔗 [Sponsor @receiver](https://github.com/sponsors/receiver)\n\n*Note: GitHub Sponsors does not support automated payments via API. Please complete the transaction manually by selecting "One-time" on the sponsor page and entering your desired amount.*',
        '⚠️ Invalid /tip command format. Use: `/tip @username $amount`\n\nExample: `/tip @contributor $10`'
      ];

      // Each comment should end with the attribution
      testComments.forEach((comment, index) => {
        const commentWithAttribution = comment + attribution;
        const expectedLink = '[OWASP BLT-Action](https://github.com/OWASP-BLT/BLT-Action)';
        assert.ok(
          commentWithAttribution.includes('OWASP BLT-Action'),
          `Comment ${index + 1} should include attribution`
        );
        assert.ok(
          commentWithAttribution.includes(expectedLink),
          `Comment ${index + 1} should include the exact attribution link format`
        );
      });
    });

    it('should have consistent attribution format', () => {
      const expectedAttribution = '\n\n---\n*This comment was generated by [OWASP BLT-Action](https://github.com/OWASP-BLT/BLT-Action)*';
      assert.strictEqual(attribution, expectedAttribution, 'Attribution format should be consistent');
    });
  });

  describe('Error Handling', () => {
    it('should handle GitHub API errors gracefully', async () => {
      const owner = 'testowner';
      const repo = 'testrepo';
      const issueNumber = 1;
      const username = 'testuser';

      const scope = nock('https://api.github.com')
        .post(`/repos/${owner}/${repo}/issues/${issueNumber}/assignees`, { assignees: [username] })
        .reply(500, { message: 'Internal Server Error' });

      try {
        await assignUserToIssue(owner, repo, issueNumber, username);
        assert.fail('Should have thrown an error');
      } catch (error) {
        assert.ok(error.message.includes('500'));
      }

      scope.done();
    });

    it('should handle Giphy API errors gracefully', async () => {
      const owner = 'testowner';
      const repo = 'testrepo';
      const issueNumber = 1;
      const searchText = 'test';
      const giphyApiKey = 'testapikey';

      const giphyScope = nock('https://api.giphy.com')
        .get(`/v1/gifs/search?api_key=${giphyApiKey}&q=${searchText}&limit=1`)
        .reply(403, { message: 'Forbidden' });

      try {
        await postGiphyComment(owner, repo, issueNumber, searchText, giphyApiKey);
        assert.fail('Should have thrown an error');
      } catch (error) {
        assert.ok(error.message.includes('403'));
      }

      giphyScope.done();
    });

    it('should handle Kudos API errors gracefully', async () => {
      const sender = 'testsender';
      const receiver = '@testreceiver';
      const comment = 'great work';
      const link = 'https://github.com/owner/repo/issues/1';

      const scope = nock('https://owaspblt.org')
        .post('/teams/give-kudos/', {
          kudosReceiver: receiver,
          kudosSender: sender,
          link: link,
          comment: comment
        })
        .reply(500, { message: 'Internal Server Error' });

      try {
        await sendKudos(sender, receiver, comment, link);
        assert.fail('Should have thrown an error');
      } catch (error) {
        assert.ok(error.message.includes('500'));
      }

      scope.done();
    });
  });
  describe('PR Assignment Command Feedback', () => {
    beforeEach(() => {
      nock.cleanAll();
    });

    afterEach(() => {
      nock.cleanAll();
    });

    describe('Assignment Commands on Pull Requests', () => {
      it('should post feedback comment when /assign is used on a PR comment', async () => {
        const owner = 'testowner';
        const repo = 'testrepo';
        const prNumber = 123;
        const username = 'testuser';
        
        // Mock the GitHub API call for creating a feedback comment
        const commentScope = nock('https://api.github.com')
          .post(`/repos/${owner}/${repo}/issues/${prNumber}/comments`, (body) => {
            // Verify the comment body contains expected feedback text
            return body.body.includes('⚠️ **Assignment commands only work on issues**') &&
                  body.body.includes('/assign') &&
                  body.body.includes('Pull requests are linked to issues') &&
                  body.body.includes('navigate to the related issue') &&
                  body.body.includes(attribution);
          })
          .reply(201, {
            id: 1,
            body: 'Comment created successfully'
          });

        // Simulate posting a feedback comment (this mimics what the fixed code should do)
        const url = `https://api.github.com/repos/${owner}/${repo}/issues/${prNumber}/comments`;
        await axios.post(url, {
          body: `⚠️ **Assignment commands only work on issues**\n\n` +
                `The \`/assign\` command cannot be used on pull requests. ` +
                `Pull requests are linked to issues, and assignment should be done on the issue itself.\n\n` +
                `💡 **Tip:** Please navigate to the related issue and use \`/assign\` there to get assigned.${attribution}`
        });

        // Verify the API was called as expected
        assert.ok(commentScope.isDone(), 'Feedback comment should be posted to PR');
      });

      it('should post feedback comment when /unassign is used on a PR comment', async () => {
        const owner = 'testowner';
        const repo = 'testrepo';
        const prNumber = 456;
        const username = 'testuser';
        
        // Mock the GitHub API call for creating a feedback comment
        const commentScope = nock('https://api.github.com')
          .post(`/repos/${owner}/${repo}/issues/${prNumber}/comments`, (body) => {
            // Verify the comment body contains expected feedback text
            return body.body.includes('⚠️ **Assignment commands only work on issues**') &&
                  body.body.includes('/unassign') &&
                  body.body.includes('cannot be used on pull requests') &&
                  body.body.includes('navigate to the issue') &&
                  body.body.includes(attribution);
          })
          .reply(201, {
            id: 2,
            body: 'Comment created successfully'
          });

        // Simulate posting a feedback comment (this mimics what the fixed code should do)
        const url = `https://api.github.com/repos/${owner}/${repo}/issues/${prNumber}/comments`;
        await axios.post(url, {
          body: `⚠️ **Assignment commands only work on issues**\n\n` +
                `The \`/unassign\` command cannot be used on pull requests. ` +
                `If you want to unassign yourself from the related issue, please navigate to the issue and use \`/unassign\` there.\n\n` +
                `💡 **Tip:** Assignment commands (\`/assign\`, \`/unassign\`) are only available on issue comments.${attribution}`
        });

        // Verify the API was called as expected
        assert.ok(commentScope.isDone(), 'Feedback comment should be posted to PR');
      });

      it('should NOT assign when /assign is used on a PR', async () => {
        const owner = 'testowner';
        const repo = 'testrepo';
        const prNumber = 789;
        const username = 'testuser';
        
        // Mock ONLY the comment creation, NOT the assignment API
        const commentScope = nock('https://api.github.com')
          .post(`/repos/${owner}/${repo}/issues/${prNumber}/comments`)
          .reply(201, { id: 3 });

        // Ensure assignment API is NOT called
        const assignScope = nock('https://api.github.com')
          .post(`/repos/${owner}/${repo}/issues/${prNumber}/assignees`)
          .reply(201, { status: 'This should NOT be called' });

        // Simulate the fixed logic: detect PR context and only post feedback
        const isPullRequest = true; // Simulating issue.pull_request exists
        
        if (!isPullRequest) {
          // This should NOT execute for PRs
          await axios.post(`https://api.github.com/repos/${owner}/${repo}/issues/${prNumber}/assignees`, {
            assignees: [username]
          });
        } else {
          // Only post feedback for PRs
          await axios.post(`https://api.github.com/repos/${owner}/${repo}/issues/${prNumber}/comments`, {
            body: `⚠️ **Assignment commands only work on issues**\n\n` +
                  `The \`/assign\` command cannot be used on pull requests.${attribution}`
          });
        }

        // Verify feedback comment was posted
        assert.ok(commentScope.isDone(), 'Feedback comment should be posted');
        
        // Verify assignment API was NOT called
        assert.ok(!assignScope.isDone(), 'Assignment API should NOT be called on PRs');
      });

      it('should include attribution footer in all PR feedback comments', async () => {
        const owner = 'testowner';
        const repo = 'testrepo';
        const prNumber = 999;
        
        // Mock comment creation and verify attribution is included
        const commentScope = nock('https://api.github.com')
          .post(`/repos/${owner}/${repo}/issues/${prNumber}/comments`, (body) => {
            // Verify attribution footer format
            return body.body.includes('\n\n---\n*This comment was generated by [OWASP BLT-Action](https://github.com/OWASP-BLT/BLT-Action)*');
          })
          .reply(201, { id: 4 });

        // Simulate posting feedback with attribution
        await axios.post(`https://api.github.com/repos/${owner}/${repo}/issues/${prNumber}/comments`, {
          body: `⚠️ **Assignment commands only work on issues**\n\nTest message.${attribution}`
        });

        assert.ok(commentScope.isDone(), 'Attribution should be included in feedback');
      });
    });

    describe('PR Context Detection', () => {
      it('should detect PR context when issue.pull_request is defined', () => {
        // Simulate GitHub's issue object for a PR comment
        const prIssueObject = {
          number: 123,
          title: 'Test PR',
          pull_request: {
            url: 'https://api.github.com/repos/owner/repo/pulls/123'
          }
        };

        // Simulate GitHub's issue object for a regular issue
        const regularIssueObject = {
          number: 456,
          title: 'Test Issue'
          // No pull_request property
        };

        // Test PR detection logic
        const isPR = prIssueObject.pull_request !== undefined;
        const isIssue = regularIssueObject.pull_request === undefined;

        assert.ok(isPR, 'Should detect PR when issue.pull_request exists');
        assert.ok(isIssue, 'Should detect regular issue when issue.pull_request is undefined');
      });

      it('should correctly evaluate the fixed guard condition', () => {
        // Test cases for the guard: if (!issue || issue.pull_request)
        
        // Case 1: No issue context (pull_request_review_comment event)
        const noIssue = null;
        const shouldSkip1 = !noIssue || (noIssue && noIssue.pull_request);
        assert.ok(shouldSkip1, 'Should skip when no issue context');

        // Case 2: PR comment (issue_comment event on PR)
        const prIssue = { number: 123, pull_request: { url: 'test' } };
        const shouldSkip2 = !prIssue || (prIssue && prIssue.pull_request);
        assert.ok(shouldSkip2, 'Should skip when issue.pull_request exists');

        // Case 3: Regular issue comment
        const regularIssue = { number: 456 };
        const shouldSkip3 = !regularIssue || (regularIssue && regularIssue.pull_request);
        assert.ok(!shouldSkip3, 'Should NOT skip for regular issues');
      });
    });

    describe('Assignment Should Work on Issues Only', () => {
      it('should allow assignment on regular issues', async () => {
        const owner = 'testowner';
        const repo = 'testrepo';
        const issueNumber = 100;
        const username = 'testuser';

        // Mock successful assignment on a regular issue
        const assignScope = nock('https://api.github.com')
          .post(`/repos/${owner}/${repo}/issues/${issueNumber}/assignees`, {
            assignees: [username]
          })
          .reply(201, { status: 'success' });

        // Simulate assignment on a regular issue (no pull_request property)
        const issue = { number: issueNumber }; // Regular issue
        const isPR = issue.pull_request !== undefined;

        if (!isPR) {
          await axios.post(`https://api.github.com/repos/${owner}/${repo}/issues/${issueNumber}/assignees`, {
            assignees: [username]
          });
        }

        assert.ok(assignScope.isDone(), 'Assignment should work on regular issues');
      });
    });
  });
});