name: Auto Assign & Bounty Bot

on:
  issue_comment:
    types: [created]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issues
        uses: OWASP/BLT-Action@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }} 
    continue-on-error: true  # Allow next job to run if this fails

  bounty:
    runs-on: ubuntu-latest
    needs: auto-assign
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install @octokit/rest @slack/web-api

      - name: Capture GitHub Context
        run: echo '${{ toJson(github.event) }}' > github_context.json

      - name: Run Bounty Bot
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: node src/index.js github_context.json  # Ensure this matches your file name
